/** First-segment quote aliases under /quote/:symbol/:page matching /stocks, /etf, and /funds routes. */
export const QUOTE_SUBPAGES = new Set([
  "altman-z-score",
  "assets",
  "asset-turnover",
  "book-value",
  "buybacks",
  "capex",
  "cash",
  "cash-conversion-cycle",
  "cash-ratio",
  "chart",
  "company",
  "congress",
  "constituents",
  "cost-of-revenue",
  "current-ratio",
  "days-inventory-outstanding",
  "days-payables-outstanding",
  "days-sales-outstanding",
  "debt",
  "debt-ebitda",
  "debt-equity-ratio",
  "debt-fcf",
  "depreciation-amortization",
  "dividend",
  "dividend-yield",
  "earnings",
  "earnings-yield",
  "ebit",
  "ebitda",
  "ebitda-margin",
  "ebit-margin",
  "effective-tax-rate",
  "employees",
  "enterprise-value",
  "equity",
  "esg",
  "ev-earnings",
  "ev-ebit",
  "ev-ebitda",
  "ev-fcf",
  "ev-sales",
  "fair-value",
  "fcf-margin",
  "fcf-yield",
  "filings",
  "financials",
  "forecast",
  "forward-pe",
  "forward-ps",
  "free-cash-flow",
  "fundamental-chart",
  "graham-number",
  "gross-margin",
  "gross-profit",
  "history",
  "holdings",
  "income-tax",
  "insiders",
  "interest-coverage",
  "interest-expense",
  "interest-income",
  "inventory-turnover",
  "liabilities",
  "market-cap",
  "metrics",
  "net-borrowing",
  "net-cash",
  "net-cash-per-share",
  "net-debt-ebitda",
  "net-income",
  "news",
  "operating-cash-flow",
  "operating-expenses",
  "operating-income",
  "operating-margin",
  "owner-earnings",
  "ownership",
  "payout-ratio",
  "pb-ratio",
  "peers",
  "peg-ratio",
  "pe-ratio",
  "pfcf-ratio",
  "piotroski-score",
  "pocf-ratio",
  "pretax-income",
  "pretax-margin",
  "profit-margin",
  "ps-ratio",
  "quick-ratio",
  "ratings",
  "research-and-development",
  "revenue",
  "roa",
  "roce",
  "roe",
  "roic",
  "sga",
  "shares",
  "splits",
  "statistics",
  "tangible-book-value",
  "transcripts",
  "wacc",
  "working-capital",
]);

/** First-level SA slugs that live under /financials on this clone. */
export const QUOTE_PATH_ALIASES: Record<string, string[]> = {
  "income-statement": ["financials", "income-statement"],
  "balance-sheet": ["financials", "balance-sheet"],
  "cash-flow-statement": ["financials", "cash-flow-statement"],
  "cash-flow": ["financials", "cash-flow-statement"],
  ratios: ["financials", "ratios"],
  growth: ["financials", "growth"],
  reports: ["financials", "reports"],
  executives: ["company", "executives"],
};

export function quoteSubpath(segment: string) {
  const key = segment.toLowerCase();
  if (QUOTE_PATH_ALIASES[key]) return QUOTE_PATH_ALIASES[key];
  if (QUOTE_SUBPAGES.has(key)) return [key];
  return null;
}

export function isQuoteSubpage(segment: string) {
  const key = segment.toLowerCase();
  return QUOTE_SUBPAGES.has(key) || key in QUOTE_PATH_ALIASES;
}
