export type StatementRow = {
  key: string;
  label: string;
  indent?: number;
  emphasize?: boolean;
  format?: "money" | "share" | "eps" | "ratio" | "percent" | "number";
};

export const INCOME_ROWS: StatementRow[] = [
  { key: "revenue", label: "Revenue", emphasize: true, format: "money" },
  { key: "costOfRevenue", label: "Cost of Revenue", format: "money" },
  { key: "grossProfit", label: "Gross Profit", emphasize: true, format: "money" },
  { key: "researchAndDevelopmentExpenses", label: "Research and Development", indent: 1, format: "money" },
  {
    key: "sellingGeneralAndAdministrativeExpenses",
    label: "Selling, General & Admin",
    indent: 1,
    format: "money",
  },
  { key: "operatingExpenses", label: "Operating Expenses", format: "money" },
  { key: "operatingIncome", label: "Operating Income", emphasize: true, format: "money" },
  { key: "interestIncome", label: "Interest Income", indent: 1, format: "money" },
  { key: "interestExpense", label: "Interest Expense", indent: 1, format: "money" },
  { key: "totalOtherIncomeExpensesNet", label: "Other Income / Expense", format: "money" },
  { key: "incomeBeforeTax", label: "Pretax Income", emphasize: true, format: "money" },
  { key: "incomeTaxExpense", label: "Income Tax", format: "money" },
  { key: "netIncome", label: "Net Income", emphasize: true, format: "money" },
  { key: "epsDiluted", label: "EPS (Diluted)", format: "eps" },
  { key: "weightedAverageShsOutDil", label: "Shares Outstanding (Diluted)", format: "share" },
  { key: "ebitda", label: "EBITDA", format: "money" },
];

export const BALANCE_ROWS: StatementRow[] = [
  { key: "cashAndCashEquivalents", label: "Cash & Equivalents", format: "money" },
  { key: "shortTermInvestments", label: "Short-Term Investments", format: "money" },
  { key: "cashAndShortTermInvestments", label: "Cash & Short-Term Investments", emphasize: true, format: "money" },
  { key: "netReceivables", label: "Receivables", format: "money" },
  { key: "inventory", label: "Inventory", format: "money" },
  { key: "totalCurrentAssets", label: "Total Current Assets", emphasize: true, format: "money" },
  { key: "propertyPlantEquipmentNet", label: "Property, Plant & Equipment", format: "money" },
  { key: "goodwill", label: "Goodwill", format: "money" },
  { key: "longTermInvestments", label: "Long-Term Investments", format: "money" },
  { key: "totalNonCurrentAssets", label: "Total Non-Current Assets", emphasize: true, format: "money" },
  { key: "totalAssets", label: "Total Assets", emphasize: true, format: "money" },
  { key: "accountPayables", label: "Accounts Payable", format: "money" },
  { key: "shortTermDebt", label: "Short-Term Debt", format: "money" },
  { key: "deferredRevenue", label: "Deferred Revenue", format: "money" },
  { key: "totalCurrentLiabilities", label: "Total Current Liabilities", emphasize: true, format: "money" },
  { key: "longTermDebt", label: "Long-Term Debt", format: "money" },
  { key: "totalNonCurrentLiabilities", label: "Total Non-Current Liabilities", emphasize: true, format: "money" },
  { key: "totalLiabilities", label: "Total Liabilities", emphasize: true, format: "money" },
  { key: "commonStock", label: "Common Stock", format: "money" },
  { key: "retainedEarnings", label: "Retained Earnings", format: "money" },
  { key: "totalStockholdersEquity", label: "Shareholders' Equity", emphasize: true, format: "money" },
  { key: "totalDebt", label: "Total Debt", format: "money" },
  { key: "netDebt", label: "Net Debt", format: "money" },
];

export const CASH_FLOW_ROWS: StatementRow[] = [
  { key: "netIncome", label: "Net Income", format: "money" },
  { key: "depreciationAndAmortization", label: "Depreciation & Amortization", format: "money" },
  { key: "stockBasedCompensation", label: "Stock-Based Compensation", format: "money" },
  { key: "changeInWorkingCapital", label: "Change in Working Capital", format: "money" },
  {
    key: "netCashProvidedByOperatingActivities",
    label: "Operating Cash Flow",
    emphasize: true,
    format: "money",
  },
  { key: "investmentsInPropertyPlantAndEquipment", label: "Capital Expenditures", format: "money" },
  { key: "acquisitionsNet", label: "Acquisitions", format: "money" },
  { key: "purchasesOfInvestments", label: "Purchases of Investments", format: "money" },
  { key: "salesMaturitiesOfInvestments", label: "Sales / Maturities of Investments", format: "money" },
  {
    key: "netCashProvidedByInvestingActivities",
    label: "Investing Cash Flow",
    emphasize: true,
    format: "money",
  },
  { key: "netDebtIssuance", label: "Debt Issued / Repaid", format: "money" },
  { key: "commonStockRepurchased", label: "Share Repurchases", format: "money" },
  { key: "netDividendsPaid", label: "Dividends Paid", format: "money" },
  {
    key: "netCashProvidedByFinancingActivities",
    label: "Financing Cash Flow",
    emphasize: true,
    format: "money",
  },
  { key: "netChangeInCash", label: "Net Change in Cash", format: "money" },
  { key: "freeCashFlow", label: "Free Cash Flow", emphasize: true, format: "money" },
];

export const RATIO_ROWS: StatementRow[] = [
  { key: "grossProfitMargin", label: "Gross Margin", format: "percent" },
  { key: "operatingProfitMargin", label: "Operating Margin", format: "percent" },
  { key: "netProfitMargin", label: "Profit Margin", format: "percent" },
  { key: "ebitdaMargin", label: "EBITDA Margin", format: "percent" },
  { key: "returnOnAssets", label: "Return on Assets", format: "percent" },
  { key: "returnOnEquity", label: "Return on Equity", format: "percent" },
  { key: "currentRatio", label: "Current Ratio", format: "ratio" },
  { key: "quickRatio", label: "Quick Ratio", format: "ratio" },
  { key: "debtToEquityRatio", label: "Debt / Equity", format: "ratio" },
  { key: "priceToEarningsRatio", label: "PE Ratio", format: "ratio" },
  { key: "priceToBookRatio", label: "PB Ratio", format: "ratio" },
  { key: "priceToSalesRatio", label: "PS Ratio", format: "ratio" },
  { key: "priceToFreeCashFlowRatio", label: "P/FCF", format: "ratio" },
  { key: "dividendYield", label: "Dividend Yield", format: "percent" },
  { key: "dividendPayoutRatio", label: "Payout Ratio", format: "percent" },
];

export const GROWTH_ROWS: StatementRow[] = [
  { key: "revenueGrowth", label: "Revenue Growth", emphasize: true, format: "percent" },
  { key: "grossProfitGrowth", label: "Gross Profit Growth", format: "percent" },
  { key: "operatingIncomeGrowth", label: "Operating Income Growth", format: "percent" },
  { key: "netIncomeGrowth", label: "Net Income Growth", emphasize: true, format: "percent" },
  { key: "epsdilutedGrowth", label: "EPS Growth (Diluted)", format: "percent" },
  { key: "ebitdaGrowth", label: "EBITDA Growth", format: "percent" },
  { key: "operatingCashFlowGrowth", label: "Operating Cash Flow Growth", format: "percent" },
  { key: "freeCashFlowGrowth", label: "Free Cash Flow Growth", emphasize: true, format: "percent" },
  { key: "assetGrowth", label: "Asset Growth", format: "percent" },
  { key: "bookValueperShareGrowth", label: "Book Value / Share Growth", format: "percent" },
  { key: "debtGrowth", label: "Debt Growth", format: "percent" },
  { key: "receivablesGrowth", label: "Receivables Growth", format: "percent" },
  { key: "inventoryGrowth", label: "Inventory Growth", format: "percent" },
  { key: "weightedAverageSharesDilutedGrowth", label: "Diluted Shares Growth", format: "percent" },
  { key: "dividendsPerShareGrowth", label: "Dividend / Share Growth", format: "percent" },
  { key: "rdexpenseGrowth", label: "R&D Growth", format: "percent" },
  { key: "sgaexpensesGrowth", label: "SG&A Growth", format: "percent" },
  { key: "threeYRevenueGrowthPerShare", label: "3Y Revenue / Share", format: "percent" },
  { key: "fiveYRevenueGrowthPerShare", label: "5Y Revenue / Share", format: "percent" },
  { key: "tenYRevenueGrowthPerShare", label: "10Y Revenue / Share", format: "percent" },
  { key: "threeYNetIncomeGrowthPerShare", label: "3Y Net Income / Share", format: "percent" },
  { key: "fiveYNetIncomeGrowthPerShare", label: "5Y Net Income / Share", format: "percent" },
  { key: "tenYNetIncomeGrowthPerShare", label: "10Y Net Income / Share", format: "percent" },
  { key: "threeYOperatingCFGrowthPerShare", label: "3Y Operating CF / Share", format: "percent" },
  { key: "fiveYOperatingCFGrowthPerShare", label: "5Y Operating CF / Share", format: "percent" },
  { key: "tenYOperatingCFGrowthPerShare", label: "10Y Operating CF / Share", format: "percent" },
  { key: "threeYShareholdersEquityGrowthPerShare", label: "3Y Equity / Share", format: "percent" },
  { key: "fiveYShareholdersEquityGrowthPerShare", label: "5Y Equity / Share", format: "percent" },
  { key: "tenYShareholdersEquityGrowthPerShare", label: "10Y Equity / Share", format: "percent" },
];

export const KEY_METRIC_ROWS: StatementRow[] = [
  { key: "marketCap", label: "Market Cap", emphasize: true, format: "money" },
  { key: "enterpriseValue", label: "Enterprise Value", emphasize: true, format: "money" },
  { key: "evToSales", label: "EV / Sales", format: "ratio" },
  { key: "evToEBITDA", label: "EV / EBITDA", format: "ratio" },
  { key: "evToOperatingCashFlow", label: "EV / Operating CF", format: "ratio" },
  { key: "evToFreeCashFlow", label: "EV / FCF", format: "ratio" },
  { key: "netDebtToEBITDA", label: "Net Debt / EBITDA", format: "ratio" },
  { key: "currentRatio", label: "Current Ratio", format: "ratio" },
  { key: "returnOnAssets", label: "Return on Assets", format: "percent" },
  { key: "returnOnEquity", label: "Return on Equity", format: "percent" },
  { key: "returnOnInvestedCapital", label: "Return on Invested Capital", format: "percent" },
  { key: "returnOnCapitalEmployed", label: "Return on Capital Employed", format: "percent" },
  { key: "earningsYield", label: "Earnings Yield", format: "percent" },
  { key: "freeCashFlowYield", label: "FCF Yield", format: "percent" },
  { key: "grahamNumber", label: "Graham Number", format: "eps" },
  { key: "grahamNetNet", label: "Graham Net-Net", format: "eps" },
  { key: "workingCapital", label: "Working Capital", format: "money" },
  { key: "investedCapital", label: "Invested Capital", format: "money" },
  { key: "freeCashFlowToEquity", label: "FCFE", format: "money" },
  { key: "incomeQuality", label: "Income Quality", format: "ratio" },
  { key: "capexToRevenue", label: "Capex / Revenue", format: "percent" },
  { key: "stockBasedCompensationToRevenue", label: "SBC / Revenue", format: "percent" },
  { key: "researchAndDevelopementToRevenue", label: "R&D / Revenue", format: "percent" },
  { key: "operatingCycle", label: "Operating Cycle", format: "number" },
  { key: "cashConversionCycle", label: "Cash Conversion Cycle", format: "number" },
  { key: "daysOfSalesOutstanding", label: "Days Sales Outstanding", format: "number" },
  { key: "daysOfInventoryOutstanding", label: "Days Inventory Outstanding", format: "number" },
  { key: "daysOfPayablesOutstanding", label: "Days Payables Outstanding", format: "number" },
];

export const INDEX_LABELS: Record<string, string> = {
  "^GSPC": "S&P 500",
  "^DJI": "Dow Jones",
  "^IXIC": "Nasdaq",
  "^NDX": "Nasdaq 100",
  "^RUT": "Russell 2000",
  "^VIX": "VIX",
  "^N225": "Nikkei 225",
  "^FTSE": "FTSE 100",
  "^GDAXI": "DAX",
  "^FCHI": "CAC 40",
  "^STOXX50E": "Euro Stoxx 50",
  "^SSMI": "SMI",
  "^HSI": "Hang Seng",
  "^AXJO": "S&P/ASX 200",
  "^GSPTSE": "S&P/TSX",
  "^BVSP": "Bovespa",
  "^KS11": "KOSPI",
  "^TWII": "TAIEX",
  "^BSESN": "BSE Sensex",
  "^MXX": "IPC Mexico",
  "^STI": "STI",
  "^JKSE": "Jakarta Composite",
};

export function toStatementColumns(
  rows: Array<{ fiscalYear: string; period: string; date: string }>,
  period: "annual" | "quarter",
) {
  return rows.map((row) => ({
    key: `${row.fiscalYear}-${row.period}-${row.date}`,
    label: period === "quarter" ? `${row.period} ${row.fiscalYear}` : row.fiscalYear,
    values: row as unknown as Record<string, unknown>,
  }));
}
