import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  allowedDevOrigins: ["127.0.0.1", "localhost"],
  async redirects() {
    return [
      { source: "/etf/vanguard", destination: "/list/vanguard-etfs", permanent: false },
      { source: "/etf/ishares", destination: "/list/ishares-etfs", permanent: false },
      { source: "/etf/spdr", destination: "/list/spdr-etfs", permanent: false },
      { source: "/etf/invesco", destination: "/list/invesco-etfs", permanent: false },
      { source: "/etf/schwab", destination: "/list/schwab-etfs", permanent: false },
      { source: "/list/semiconductors", destination: "/list/semiconductor-stocks", permanent: false },
      { source: "/list/reits", destination: "/list/reit-stocks", permanent: false },
      { source: "/list/banks", destination: "/list/bank-stocks", permanent: false },
      { source: "/list/airlines", destination: "/list/airline-stocks", permanent: false },
      { source: "/list/gold", destination: "/list/gold-stocks", permanent: false },
      { source: "/list/restaurants", destination: "/list/restaurant-stocks", permanent: false },
      { source: "/list/faang-stocks", destination: "/list/faang", permanent: false },
      { source: "/stocks/screener", destination: "/screener", permanent: false },
      { source: "/list/most-revenue", destination: "/list/highest-revenue", permanent: false },
      { source: "/list/most-employees", destination: "/list/highest-employees", permanent: false },
      { source: "/list/highest-tax", destination: "/list/highest-taxes", permanent: false },
      { source: "/list/solar", destination: "/list/solar-stocks", permanent: false },
      { source: "/list/ev", destination: "/list/ev-stocks", permanent: false },
      { source: "/list/cybersecurity", destination: "/list/cybersecurity-stocks", permanent: false },
      { source: "/list/retail", destination: "/list/retail-stocks", permanent: false },
      { source: "/list/most-profitable", destination: "/list/highest-profit", permanent: false },
      { source: "/list/ai", destination: "/list/ai-stocks", permanent: false },
      { source: "/list/cloud", destination: "/list/cloud-stocks", permanent: false },
      { source: "/list/healthcare", destination: "/list/healthcare-stocks", permanent: false },
      { source: "/list/fintech", destination: "/list/fintech-stocks", permanent: false },
      { source: "/list/cannabis", destination: "/list/cannabis-stocks", permanent: false },
      { source: "/list/lithium", destination: "/list/lithium-stocks", permanent: false },
      { source: "/list/copper", destination: "/list/copper-stocks", permanent: false },
      { source: "/list/silver", destination: "/list/silver-stocks", permanent: false },
      { source: "/list/coal", destination: "/list/coal-stocks", permanent: false },
      { source: "/list/commodity-etf", destination: "/list/commodity-etfs", permanent: false },
      { source: "/list/semiconductor-equipment", destination: "/list/semiconductor-equipment-stocks", permanent: false },
      { source: "/markets/world", destination: "/markets/global", permanent: false },
      { source: "/list/bdcs", destination: "/list/bdc-stocks", permanent: false },
      { source: "/list/bdc", destination: "/list/bdc-stocks", permanent: false },
      { source: "/list/cefs", destination: "/list/cef-funds", permanent: false },
      { source: "/list/closed-end-funds", destination: "/list/cef-funds", permanent: false },
      { source: "/list/preferred", destination: "/list/preferred-stocks", permanent: false },
      { source: "/list/glp-1", destination: "/list/glp1-stocks", permanent: false },
      { source: "/list/glp1", destination: "/list/glp1-stocks", permanent: false },
      { source: "/list/top-rated-stocks", destination: "/list/top-rated", permanent: false },
      { source: "/list/waste", destination: "/list/waste-management-stocks", permanent: false },
      { source: "/list/chemicals", destination: "/list/chemical-stocks", permanent: false },
      { source: "/list/apparel", destination: "/list/apparel-stocks", permanent: false },
      { source: "/list/luxury", destination: "/list/apparel-stocks", permanent: false },
      { source: "/etf/reverse-lookup", destination: "/etf/lookup", permanent: false },
      { source: "/tools/etf-lookup", destination: "/etf/lookup", permanent: false },
    ];
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "images.financialmodelingprep.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "financialmodelingprep.com",
        pathname: "/**",
      },
    ],
  },
};

export default nextConfig;
