import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  allowedDevOrigins: ["127.0.0.1", "localhost"],
  async redirects() {
    return [
      { source: "/etf/vanguard", destination: "/list/vanguard-etfs", permanent: false },
      { source: "/etf/ishares", destination: "/list/ishares-etfs", permanent: false },
      { source: "/etf/spdr", destination: "/list/spdr-etfs", permanent: false },
      { source: "/etf/invesco", destination: "/list/invesco-etfs", permanent: false },
      { source: "/etf/schwab", destination: "/list/schwab-etfs", permanent: false },
      { source: "/list/semiconductors", destination: "/list/semiconductor-stocks", permanent: false },
      { source: "/list/reits", destination: "/list/reit-stocks", permanent: false },
      { source: "/list/banks", destination: "/list/bank-stocks", permanent: false },
      { source: "/list/airlines", destination: "/list/airline-stocks", permanent: false },
      { source: "/list/gold", destination: "/list/gold-stocks", permanent: false },
      { source: "/list/restaurants", destination: "/list/restaurant-stocks", permanent: false },
      { source: "/list/faang-stocks", destination: "/list/faang", permanent: false },
      { source: "/stocks/screener", destination: "/screener", permanent: false },
      { source: "/list/most-revenue", destination: "/list/highest-revenue", permanent: false },
      { source: "/list/most-employees", destination: "/list/highest-employees", permanent: false },
      { source: "/list/most-taxes-us", destination: "/list/highest-taxes", permanent: false },
      { source: "/list/car-company-stocks", destination: "/list/auto-stocks", permanent: false },
      { source: "/list/pharmaceutical-stocks", destination: "/list/pharma-stocks", permanent: false },
      { source: "/list/pharma", destination: "/list/pharma-stocks", permanent: false },
      { source: "/list/oil-gas", destination: "/list/oil-gas-stocks", permanent: false },
      { source: "/list/utilities", destination: "/list/utilities-stocks", permanent: false },
      { source: "/list/mega-cap", destination: "/list/mega-cap-stocks", permanent: false },
      { source: "/list/tsx", destination: "/list/tsx-stocks", permanent: false },
      { source: "/list/uk-stocks", destination: "/list/london-stocks", permanent: false },
      { source: "/list/uk", destination: "/list/london-stocks", permanent: false },
      { source: "/list/streaming", destination: "/list/streaming-stocks", permanent: false },
      { source: "/list/autos", destination: "/list/auto-stocks", permanent: false },
      { source: "/list/semis", destination: "/list/semiconductor-stocks", permanent: false },
      { source: "/list/biotech", destination: "/list/biotech-stocks", permanent: false },
      { source: "/list/sp500", destination: "/list/sp-500-stocks", permanent: false },
      { source: "/list/nasdaq100", destination: "/list/nasdaq-100-stocks", permanent: false },
      { source: "/list/dow", destination: "/list/dow-jones-stocks", permanent: false },
      { source: "/list/biggest", destination: "/list/biggest-companies", permanent: false },
      { source: "/list/mag7", destination: "/list/magnificent-seven", permanent: false },
      { source: "/list/mag-7", destination: "/list/magnificent-seven", permanent: false },
      { source: "/list/aristocrats", destination: "/list/dividend-aristocrats", permanent: false },
      { source: "/list/kings", destination: "/list/dividend-kings", permanent: false },
      { source: "/list/leveraged", destination: "/list/leveraged-etfs", permanent: false },
      { source: "/list/highest-tax", destination: "/list/highest-taxes", permanent: false },
      { source: "/list/solar", destination: "/list/solar-stocks", permanent: false },
      { source: "/list/ev", destination: "/list/ev-stocks", permanent: false },
      { source: "/list/cybersecurity", destination: "/list/cybersecurity-stocks", permanent: false },
      { source: "/list/retail", destination: "/list/retail-stocks", permanent: false },
      { source: "/list/most-profitable", destination: "/list/highest-profit", permanent: false },
      { source: "/list/ai", destination: "/list/ai-stocks", permanent: false },
      { source: "/list/cloud", destination: "/list/cloud-stocks", permanent: false },
      { source: "/list/healthcare", destination: "/list/healthcare-stocks", permanent: false },
      { source: "/list/fintech", destination: "/list/fintech-stocks", permanent: false },
      { source: "/list/cannabis", destination: "/list/cannabis-stocks", permanent: false },
      { source: "/list/lithium", destination: "/list/lithium-stocks", permanent: false },
      { source: "/list/copper", destination: "/list/copper-stocks", permanent: false },
      { source: "/list/silver", destination: "/list/silver-stocks", permanent: false },
      { source: "/list/coal", destination: "/list/coal-stocks", permanent: false },
      { source: "/list/commodity-etf", destination: "/list/commodity-etfs", permanent: false },
      { source: "/list/semiconductor-equipment", destination: "/list/semiconductor-equipment-stocks", permanent: false },
      { source: "/markets/world", destination: "/markets/global", permanent: false },
      { source: "/list/bdcs", destination: "/list/bdc-stocks", permanent: false },
      { source: "/list/bdc", destination: "/list/bdc-stocks", permanent: false },
      { source: "/list/cefs", destination: "/list/cef-funds", permanent: false },
      { source: "/list/closed-end-funds", destination: "/list/cef-funds", permanent: false },
      { source: "/list/preferred", destination: "/list/preferred-stocks", permanent: false },
      { source: "/list/glp-1", destination: "/list/glp1-stocks", permanent: false },
      { source: "/list/glp1", destination: "/list/glp1-stocks", permanent: false },
      { source: "/list/top-rated-stocks", destination: "/list/top-rated", permanent: false },
      { source: "/list/waste", destination: "/list/waste-management-stocks", permanent: false },
      { source: "/list/chemicals", destination: "/list/chemical-stocks", permanent: false },
      { source: "/list/apparel", destination: "/list/apparel-stocks", permanent: false },
      { source: "/list/luxury", destination: "/list/apparel-stocks", permanent: false },
      { source: "/etf/reverse-lookup", destination: "/etf/lookup", permanent: false },
      { source: "/tools/etf-lookup", destination: "/etf/lookup", permanent: false },
      { source: "/list/bitcoin", destination: "/list/bitcoin-etfs", permanent: false },
      { source: "/list/bitcoin-etf", destination: "/list/bitcoin-etfs", permanent: false },
      { source: "/list/ethereum-etf", destination: "/list/ethereum-etfs", permanent: false },
      { source: "/list/ether-etfs", destination: "/list/ethereum-etfs", permanent: false },
      { source: "/list/top-rated-dividends", destination: "/list/top-rated-dividend-stocks", permanent: false },
      { source: "/list/top-rated-dividend", destination: "/list/top-rated-dividend-stocks", permanent: false },
      { source: "/toolkit", destination: "/tools", permanent: false },
      { source: "/tools/cagr-calculator", destination: "/tools/cagr", permanent: false },
      { source: "/tools/return", destination: "/tools/return-calculator", permanent: false },
      { source: "/tools/dividend", destination: "/tools/dividend-calculator", permanent: false },
      { source: "/etf/comparison", destination: "/etf/compare", permanent: false },
      { source: "/funds/compare", destination: "/etf/compare", permanent: false },
      { source: "/tools/etf-screener", destination: "/screener?type=etf", permanent: false },
      { source: "/tools/stock-screener", destination: "/screener", permanent: false },
      { source: "/stocks/sectors", destination: "/stocks/sector", permanent: false },
      { source: "/stocks/sectors/:slug", destination: "/stocks/sector/:slug", permanent: false },
      { source: "/crypto/:symbol", destination: "/markets/crypto/:symbol", permanent: false },
      { source: "/crypto/:symbol/news", destination: "/markets/crypto/:symbol/news", permanent: false },
      { source: "/forex/:symbol", destination: "/markets/forex/:symbol", permanent: false },
      { source: "/forex/:symbol/news", destination: "/markets/forex/:symbol/news", permanent: false },
      { source: "/commodities/:symbol", destination: "/markets/commodities/:symbol", permanent: false },
      { source: "/mutual-fund/:symbol", destination: "/funds/:symbol", permanent: false },
      { source: "/mutual-funds/:symbol", destination: "/funds/:symbol", permanent: false },
      { source: "/quote/compare", destination: "/compare", permanent: false },
      { source: "/quote/congress/:slug", destination: "/congress/:slug", permanent: false },
      { source: "/quote/13f/:cik", destination: "/institutional/:cik", permanent: false },
      { source: "/news/sec-filings", destination: "/news/filings", permanent: false },
      { source: "/news/8k", destination: "/news/filings", permanent: false },
      { source: "/earnings", destination: "/calendar/earnings", permanent: false },
      { source: "/earnings/reported", destination: "/calendar/earnings?view=reported", permanent: false },
      { source: "/crypto", destination: "/markets/crypto", permanent: false },
      { source: "/forex", destination: "/markets/forex", permanent: false },
      { source: "/stock-market-hours", destination: "/markets/hours", permanent: false },
      { source: "/market-hours", destination: "/markets/hours", permanent: false },
      { source: "/markets/index", destination: "/markets/indexes", permanent: false },
      { source: "/indexes", destination: "/markets/indexes", permanent: false },
      { source: "/market-indexes", destination: "/markets/indexes", permanent: false },
      { source: "/stocks/countries", destination: "/stocks/country", permanent: false },
      { source: "/stocks/:symbol/income-statement", destination: "/stocks/:symbol/financials/income-statement", permanent: false },
      { source: "/stocks/:symbol/balance-sheet", destination: "/stocks/:symbol/financials/balance-sheet", permanent: false },
      { source: "/stocks/:symbol/cash-flow-statement", destination: "/stocks/:symbol/financials/cash-flow-statement", permanent: false },
      { source: "/stocks/:symbol/cash-flow", destination: "/stocks/:symbol/financials/cash-flow-statement", permanent: false },
      { source: "/stocks/:symbol/ratios", destination: "/stocks/:symbol/financials/ratios", permanent: false },
      { source: "/stocks/:symbol/growth", destination: "/stocks/:symbol/financials/growth", permanent: false },
      { source: "/stocks/:symbol/reports", destination: "/stocks/:symbol/financials/reports", permanent: false },
      { source: "/stocks/exchanges", destination: "/list/exchanges", permanent: false },
      { source: "/exchanges", destination: "/list/exchanges", permanent: false },
      { source: "/list/nyseamerican-stocks", destination: "/list/nyse-american-stocks", permanent: false },
      { source: "/list/electric-vehicles", destination: "/list/ev-stocks", permanent: false },
      { source: "/list/business-development-companies", destination: "/list/bdc-stocks", permanent: false },
      { source: "/list/london-stock-exchange", destination: "/list/lse-stocks", permanent: false },
      { source: "/list/lse", destination: "/list/lse-stocks", permanent: false },
      { source: "/list/tokyo-stock-exchange", destination: "/list/japan-stocks", permanent: false },
      { source: "/list/euronext-paris", destination: "/list/paris-stocks", permanent: false },
      { source: "/list/paris", destination: "/list/paris-stocks", permanent: false },
      { source: "/list/fixed-income-etfs", destination: "/list/bond-etfs", permanent: false },
      { source: "/list/mutual-funds", destination: "/funds", permanent: false },
      { source: "/list/frankfurt-stock-exchange", destination: "/list/frankfurt-stocks", permanent: false },
      { source: "/list/clean-energy-stocks", destination: "/list/clean-energy", permanent: false },
      { source: "/list/spacs", destination: "/list/spac-stocks", permanent: false },
      { source: "/list/ai-etfs", destination: "/list/artificial-intelligence-etfs", permanent: false },
      { source: "/list/australia-etfs", destination: "/list/australian-etfs", permanent: false },
      { source: "/list/canada-etfs", destination: "/list/canadian-etfs", permanent: false },
      { source: "/list/online-gambling-stocks", destination: "/list/online-gambling", permanent: false },
      { source: "/list/shanghai-stock-exchange", destination: "/list/shanghai-stocks", permanent: false },
      { source: "/list/korea-stock-exchange", destination: "/list/korea-stocks", permanent: false },
      { source: "/list/south-korea-stocks", destination: "/list/korea-stocks", permanent: false },
      { source: "/list/cse-stocks", destination: "/list/canadian-securities-exchange", permanent: false },
      { source: "/list/neo-exchange", destination: "/list/cboe-canada", permanent: false },
      { source: "/list/taipei-stocks", destination: "/list/taipei-exchange", permanent: false },
      { source: "/list/six-swiss-exchange", destination: "/list/six-stocks", permanent: false },
      { source: "/list/six", destination: "/list/six-stocks", permanent: false },
      { source: "/list/switzerland-stocks", destination: "/list/swiss-stocks", permanent: false },
      { source: "/list/taiwan-stock-exchange", destination: "/list/taiwan-stocks", permanent: false },
      { source: "/list/singapore-exchange", destination: "/list/sgx-stocks", permanent: false },
      { source: "/list/sgx", destination: "/list/sgx-stocks", permanent: false },
      { source: "/list/euronext-amsterdam", destination: "/list/ams-stocks", permanent: false },
      { source: "/list/ams", destination: "/list/ams-stocks", permanent: false },
      { source: "/list/netherlands-stocks", destination: "/list/amsterdam-stocks", permanent: false },
      { source: "/list/borsa-italiana", destination: "/list/italy-stocks", permanent: false },
      { source: "/list/madrid-stock-exchange", destination: "/list/madrid-stocks", permanent: false },
      { source: "/list/bolsa-madrid", destination: "/list/madrid-stocks", permanent: false },
      { source: "/list/madrid", destination: "/list/madrid-stocks", permanent: false },
      { source: "/list/nasdaq-stockholm", destination: "/list/stockholm-stocks", permanent: false },
      { source: "/list/stockholm", destination: "/list/stockholm-stocks", permanent: false },
      { source: "/list/mexican-stock-exchange", destination: "/list/mex-stocks", permanent: false },
      { source: "/list/bmv", destination: "/list/mex-stocks", permanent: false },
      { source: "/list/mex", destination: "/list/mex-stocks", permanent: false },
      { source: "/list/copenhagen-stock-exchange", destination: "/list/copenhagen-stocks", permanent: false },
      { source: "/list/nasdaq-copenhagen", destination: "/list/copenhagen-stocks", permanent: false },
      { source: "/list/copenhagen", destination: "/list/copenhagen-stocks", permanent: false },
      { source: "/list/oslo-bors", destination: "/list/norway-stocks", permanent: false },
      { source: "/list/tel-aviv-stock-exchange", destination: "/list/israel-stocks", permanent: false },
      { source: "/list/johannesburg-stock-exchange", destination: "/list/jse-stocks", permanent: false },
      { source: "/list/jse", destination: "/list/jse-stocks", permanent: false },
      { source: "/list/new-zealand-stock-exchange", destination: "/list/nzx-stocks", permanent: false },
      { source: "/list/nzx", destination: "/list/nzx-stocks", permanent: false },
      { source: "/list/warsaw-stock-exchange", destination: "/list/warsaw-stocks", permanent: false },
      { source: "/list/gpw", destination: "/list/warsaw-stocks", permanent: false },
      { source: "/list/euronext-brussels", destination: "/list/brussels-stocks", permanent: false },
      { source: "/list/brussels", destination: "/list/brussels-stocks", permanent: false },
      { source: "/list/nasdaq-helsinki", destination: "/list/helsinki-stocks", permanent: false },
      { source: "/list/helsinki", destination: "/list/helsinki-stocks", permanent: false },
      { source: "/list/indonesia-stock-exchange", destination: "/list/indonesia-stocks", permanent: false },
      { source: "/list/bursa-malaysia", destination: "/list/malaysia-stocks", permanent: false },
      { source: "/list/vienna-stock-exchange", destination: "/list/vienna-stocks", permanent: false },
      { source: "/list/wiener-borse", destination: "/list/vienna-stocks", permanent: false },
      { source: "/list/dxe", destination: "/list/cboe-europe", permanent: false },
      { source: "/list/bats-chi-x", destination: "/list/cboe-europe", permanent: false },
      { source: "/list/athens-stock-exchange", destination: "/list/athens-stocks", permanent: false },
      { source: "/list/athens", destination: "/list/athens-stocks", permanent: false },
      { source: "/list/borsa-istanbul", destination: "/list/turkey-stocks", permanent: false },
      { source: "/list/stock-exchange-of-thailand", destination: "/list/thailand-stocks", permanent: false },
      { source: "/list/saudi-stock-exchange", destination: "/list/saudi-stocks", permanent: false },
      { source: "/list/qatar-stock-exchange", destination: "/list/qatar-stocks", permanent: false },
      { source: "/list/santiago-stock-exchange", destination: "/list/chile-stocks", permanent: false },
      { source: "/list/euronext-lisbon", destination: "/list/lisbon-stocks", permanent: false },
      { source: "/list/lisbon", destination: "/list/lisbon-stocks", permanent: false },
      { source: "/list/euronext-dublin", destination: "/list/dublin-stocks", permanent: false },
      { source: "/list/ireland-stocks", destination: "/list/dublin-stocks", permanent: false },
      { source: "/list/dubai-financial-market", destination: "/list/dubai-stocks", permanent: false },
      { source: "/list/toronto-stock-exchange", destination: "/list/toronto-stocks", permanent: false },
      { source: "/list/australian-securities-exchange", destination: "/list/asx-stocks", permanent: false },
      { source: "/list/asx", destination: "/list/asx-stocks", permanent: false },
      { source: "/list/buenos-aires-stock-exchange", destination: "/list/bcba-stocks", permanent: false },
      { source: "/list/byma", destination: "/list/bcba-stocks", permanent: false },
      { source: "/list/nasdaq-iceland", destination: "/list/iceland-stocks", permanent: false },
      { source: "/list/moscow-stock-exchange", destination: "/list/moscow-stocks", permanent: false },
      { source: "/list/moex", destination: "/list/moscow-stocks", permanent: false },
      { source: "/list/mcx", destination: "/list/moscow-stocks", permanent: false },
      { source: "/list/monthly-etfs", destination: "/list/monthly-dividend-etfs", permanent: false },
      { source: "/list/monthly-dividend-etf", destination: "/list/monthly-dividend-etfs", permanent: false },
      { source: "/list/weekly-etfs", destination: "/list/weekly-dividend-etfs", permanent: false },
      { source: "/list/weekly-dividend-etf", destination: "/list/weekly-dividend-etfs", permanent: false },
      { source: "/list/etn", destination: "/list/exchange-traded-notes", permanent: false },
      { source: "/list/etns", destination: "/list/exchange-traded-notes", permanent: false },
      { source: "/list/exchange-traded-note", destination: "/list/exchange-traded-notes", permanent: false },
      { source: "/list/covered-call", destination: "/list/covered-call-etfs", permanent: false },
      { source: "/list/buywrite-etfs", destination: "/list/covered-call-etfs", permanent: false },
      { source: "/list/prague-stock-exchange", destination: "/list/prague-stocks", permanent: false },
      { source: "/list/czech-stocks", destination: "/list/prague-stocks", permanent: false },
      { source: "/list/tsx-venture-exchange", destination: "/list/tsx-venture-stocks", permanent: false },
      { source: "/list/bombay-stock-exchange", destination: "/list/bse-india", permanent: false },
      { source: "/list/kosdaq-korea", destination: "/list/kosdaq-stocks", permanent: false },
      { source: "/list/dusseldorf-stock-exchange", destination: "/list/dusseldorf-stocks", permanent: false },
      { source: "/list/hamburg-stock-exchange", destination: "/list/hamburg-stocks", permanent: false },
      { source: "/list/munich-stock-exchange", destination: "/list/munich-stocks", permanent: false },
      { source: "/list/stuttgart-stock-exchange", destination: "/list/stuttgart-stocks", permanent: false },
    ];
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "images.financialmodelingprep.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "financialmodelingprep.com",
        pathname: "/**",
      },
    ],
  },
};

export default nextConfig;
