import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  allowedDevOrigins: ["127.0.0.1", "localhost"],
  async redirects() {
    return [
      { source: "/etf/vanguard", destination: "/list/vanguard-etfs", permanent: false },
      { source: "/etf/ishares", destination: "/list/ishares-etfs", permanent: false },
      { source: "/etf/spdr", destination: "/list/spdr-etfs", permanent: false },
      { source: "/etf/invesco", destination: "/list/invesco-etfs", permanent: false },
      { source: "/etf/schwab", destination: "/list/schwab-etfs", permanent: false },
      { source: "/list/semiconductors", destination: "/list/semiconductor-stocks", permanent: false },
      { source: "/list/reits", destination: "/list/reit-stocks", permanent: false },
      { source: "/list/banks", destination: "/list/bank-stocks", permanent: false },
      { source: "/list/airlines", destination: "/list/airline-stocks", permanent: false },
      { source: "/list/gold", destination: "/list/gold-stocks", permanent: false },
      { source: "/list/restaurants", destination: "/list/restaurant-stocks", permanent: false },
      { source: "/list/faang-stocks", destination: "/list/faang", permanent: false },
      { source: "/stocks/screener", destination: "/screener", permanent: false },
      { source: "/list/most-revenue", destination: "/list/highest-revenue", permanent: false },
      { source: "/list/most-employees", destination: "/list/highest-employees", permanent: false },
      { source: "/list/most-taxes-us", destination: "/list/highest-taxes", permanent: false },
      { source: "/list/car-company-stocks", destination: "/list/auto-stocks", permanent: false },
      { source: "/list/pharmaceutical-stocks", destination: "/list/pharma-stocks", permanent: false },
      { source: "/list/pharma", destination: "/list/pharma-stocks", permanent: false },
      { source: "/list/oil-gas", destination: "/list/oil-gas-stocks", permanent: false },
      { source: "/list/utilities", destination: "/list/utilities-stocks", permanent: false },
      { source: "/list/mega-cap", destination: "/list/mega-cap-stocks", permanent: false },
      { source: "/list/tsx", destination: "/list/tsx-stocks", permanent: false },
      { source: "/list/uk-stocks", destination: "/list/london-stocks", permanent: false },
      { source: "/list/uk", destination: "/list/london-stocks", permanent: false },
      { source: "/list/streaming", destination: "/list/streaming-stocks", permanent: false },
      { source: "/list/autos", destination: "/list/auto-stocks", permanent: false },
      { source: "/list/semis", destination: "/list/semiconductor-stocks", permanent: false },
      { source: "/list/biotech", destination: "/list/biotech-stocks", permanent: false },
      { source: "/list/sp500", destination: "/list/sp-500-stocks", permanent: false },
      { source: "/list/nasdaq100", destination: "/list/nasdaq-100-stocks", permanent: false },
      { source: "/list/dow", destination: "/list/dow-jones-stocks", permanent: false },
      { source: "/list/biggest", destination: "/list/biggest-companies", permanent: false },
      { source: "/list/mag7", destination: "/list/magnificent-seven", permanent: false },
      { source: "/list/mag-7", destination: "/list/magnificent-seven", permanent: false },
      { source: "/list/aristocrats", destination: "/list/dividend-aristocrats", permanent: false },
      { source: "/list/kings", destination: "/list/dividend-kings", permanent: false },
      { source: "/list/leveraged", destination: "/list/leveraged-etfs", permanent: false },
      { source: "/list/highest-tax", destination: "/list/highest-taxes", permanent: false },
      { source: "/list/solar", destination: "/list/solar-stocks", permanent: false },
      { source: "/list/ev", destination: "/list/ev-stocks", permanent: false },
      { source: "/list/cybersecurity", destination: "/list/cybersecurity-stocks", permanent: false },
      { source: "/list/retail", destination: "/list/retail-stocks", permanent: false },
      { source: "/list/most-profitable", destination: "/list/highest-profit", permanent: false },
      { source: "/list/ai", destination: "/list/ai-stocks", permanent: false },
      { source: "/list/cloud", destination: "/list/cloud-stocks", permanent: false },
      { source: "/list/healthcare", destination: "/list/healthcare-stocks", permanent: false },
      { source: "/list/fintech", destination: "/list/fintech-stocks", permanent: false },
      { source: "/list/cannabis", destination: "/list/cannabis-stocks", permanent: false },
      { source: "/list/lithium", destination: "/list/lithium-stocks", permanent: false },
      { source: "/list/copper", destination: "/list/copper-stocks", permanent: false },
      { source: "/list/silver", destination: "/list/silver-stocks", permanent: false },
      { source: "/list/coal", destination: "/list/coal-stocks", permanent: false },
      { source: "/list/commodity-etf", destination: "/list/commodity-etfs", permanent: false },
      { source: "/list/semiconductor-equipment", destination: "/list/semiconductor-equipment-stocks", permanent: false },
      { source: "/markets/world", destination: "/markets/global", permanent: false },
      { source: "/list/bdcs", destination: "/list/bdc-stocks", permanent: false },
      { source: "/list/bdc", destination: "/list/bdc-stocks", permanent: false },
      { source: "/list/cefs", destination: "/list/cef-funds", permanent: false },
      { source: "/list/closed-end-funds", destination: "/list/cef-funds", permanent: false },
      { source: "/list/preferred", destination: "/list/preferred-stocks", permanent: false },
      { source: "/list/glp-1", destination: "/list/glp1-stocks", permanent: false },
      { source: "/list/glp1", destination: "/list/glp1-stocks", permanent: false },
      { source: "/list/top-rated-stocks", destination: "/list/top-rated", permanent: false },
      { source: "/list/waste", destination: "/list/waste-management-stocks", permanent: false },
      { source: "/list/chemicals", destination: "/list/chemical-stocks", permanent: false },
      { source: "/list/apparel", destination: "/list/apparel-stocks", permanent: false },
      { source: "/list/luxury", destination: "/list/apparel-stocks", permanent: false },
      { source: "/etf/reverse-lookup", destination: "/etf/lookup", permanent: false },
      { source: "/tools/etf-lookup", destination: "/etf/lookup", permanent: false },
      { source: "/list/bitcoin", destination: "/list/bitcoin-etfs", permanent: false },
      { source: "/list/bitcoin-etf", destination: "/list/bitcoin-etfs", permanent: false },
      { source: "/list/ethereum-etf", destination: "/list/ethereum-etfs", permanent: false },
      { source: "/list/ether-etfs", destination: "/list/ethereum-etfs", permanent: false },
      { source: "/list/top-rated-dividends", destination: "/list/top-rated-dividend-stocks", permanent: false },
      { source: "/list/top-rated-dividend", destination: "/list/top-rated-dividend-stocks", permanent: false },
      { source: "/toolkit", destination: "/tools", permanent: false },
      { source: "/tools/cagr-calculator", destination: "/tools/cagr", permanent: false },
      { source: "/tools/return", destination: "/tools/return-calculator", permanent: false },
      { source: "/tools/dividend", destination: "/tools/dividend-calculator", permanent: false },
      { source: "/etf/comparison", destination: "/etf/compare", permanent: false },
      { source: "/funds/compare", destination: "/etf/compare", permanent: false },
      { source: "/tools/etf-screener", destination: "/screener?type=etf", permanent: false },
      { source: "/tools/stock-screener", destination: "/screener", permanent: false },
      { source: "/stocks/sectors", destination: "/stocks/sector", permanent: false },
      { source: "/stocks/sectors/:slug", destination: "/stocks/sector/:slug", permanent: false },
      { source: "/crypto/:symbol", destination: "/markets/crypto/:symbol", permanent: false },
      { source: "/forex/:symbol", destination: "/markets/forex/:symbol", permanent: false },
      { source: "/commodities/:symbol", destination: "/markets/commodities/:symbol", permanent: false },
      { source: "/mutual-fund/:symbol", destination: "/funds/:symbol", permanent: false },
      { source: "/mutual-funds/:symbol", destination: "/funds/:symbol", permanent: false },
      { source: "/quote/compare", destination: "/compare", permanent: false },
      { source: "/quote/congress/:slug", destination: "/congress/:slug", permanent: false },
      { source: "/quote/13f/:cik", destination: "/institutional/:cik", permanent: false },
      { source: "/news/sec-filings", destination: "/news/filings", permanent: false },
      { source: "/news/8k", destination: "/news/filings", permanent: false },
      { source: "/earnings", destination: "/calendar/earnings", permanent: false },
      { source: "/earnings/reported", destination: "/calendar/earnings?view=reported", permanent: false },
      { source: "/crypto", destination: "/markets/crypto", permanent: false },
      { source: "/forex", destination: "/markets/forex", permanent: false },
      { source: "/stock-market-hours", destination: "/markets/hours", permanent: false },
      { source: "/market-hours", destination: "/markets/hours", permanent: false },
      { source: "/markets/index", destination: "/markets/indexes", permanent: false },
      { source: "/indexes", destination: "/markets/indexes", permanent: false },
      { source: "/market-indexes", destination: "/markets/indexes", permanent: false },
      { source: "/stocks/countries", destination: "/stocks/country", permanent: false },
      { source: "/list/korea-stocks", destination: "/stocks/country/kr", permanent: false },
      { source: "/list/south-korea-stocks", destination: "/stocks/country/kr", permanent: false },
      { source: "/list/taiwan-stocks", destination: "/stocks/country/tw", permanent: false },
      { source: "/list/switzerland-stocks", destination: "/stocks/country/ch", permanent: false },
      { source: "/list/swiss-stocks", destination: "/stocks/country/ch", permanent: false },
      { source: "/list/singapore-stocks", destination: "/stocks/country/sg", permanent: false },
      { source: "/list/netherlands-stocks", destination: "/stocks/country/nl", permanent: false },
      { source: "/list/italy-stocks", destination: "/stocks/country/it", permanent: false },
      { source: "/list/spain-stocks", destination: "/stocks/country/es", permanent: false },
      { source: "/list/mexico-stocks", destination: "/stocks/country/mx", permanent: false },
      { source: "/list/sweden-stocks", destination: "/stocks/country/se", permanent: false },
      { source: "/list/denmark-stocks", destination: "/stocks/country/dk", permanent: false },
      { source: "/list/norway-stocks", destination: "/stocks/country/no", permanent: false },
      { source: "/list/israel-stocks", destination: "/stocks/country/il", permanent: false },
      { source: "/list/south-africa-stocks", destination: "/stocks/country/za", permanent: false },
      { source: "/list/poland-stocks", destination: "/stocks/country/pl", permanent: false },
      { source: "/list/belgium-stocks", destination: "/stocks/country/be", permanent: false },
      { source: "/list/new-zealand-stocks", destination: "/stocks/country/nz", permanent: false },
      { source: "/list/finland-stocks", destination: "/stocks/country/fi", permanent: false },
      { source: "/list/austria-stocks", destination: "/stocks/country/at", permanent: false },
      { source: "/stocks/:symbol/income-statement", destination: "/stocks/:symbol/financials/income-statement", permanent: false },
      { source: "/stocks/:symbol/balance-sheet", destination: "/stocks/:symbol/financials/balance-sheet", permanent: false },
      { source: "/stocks/:symbol/cash-flow-statement", destination: "/stocks/:symbol/financials/cash-flow-statement", permanent: false },
      { source: "/stocks/:symbol/cash-flow", destination: "/stocks/:symbol/financials/cash-flow-statement", permanent: false },
      { source: "/stocks/:symbol/ratios", destination: "/stocks/:symbol/financials/ratios", permanent: false },
      { source: "/stocks/:symbol/growth", destination: "/stocks/:symbol/financials/growth", permanent: false },
      { source: "/stocks/:symbol/reports", destination: "/stocks/:symbol/financials/reports", permanent: false },
      { source: "/stocks/exchanges", destination: "/list/exchanges", permanent: false },
      { source: "/exchanges", destination: "/list/exchanges", permanent: false },
      { source: "/list/nyseamerican-stocks", destination: "/list/nyse-american-stocks", permanent: false },
      { source: "/list/electric-vehicles", destination: "/list/ev-stocks", permanent: false },
      { source: "/list/business-development-companies", destination: "/list/bdc-stocks", permanent: false },
      { source: "/list/london-stock-exchange", destination: "/list/london-stocks", permanent: false },
      { source: "/list/tokyo-stock-exchange", destination: "/list/japan-stocks", permanent: false },
      { source: "/list/fixed-income-etfs", destination: "/list/bond-etfs", permanent: false },
      { source: "/list/covered-call-etfs", destination: "/list/income-etfs", permanent: false },
      { source: "/list/mutual-funds", destination: "/funds", permanent: false },
    ];
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "images.financialmodelingprep.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "financialmodelingprep.com",
        pathname: "/**",
      },
    ],
  },
};

export default nextConfig;
