import { StatementMetricPage, periodFrom } from "@/components/statement-metric-page";
import { decodeTicker } from "@/lib/listings";

export default async function OperatingCashFlowPage({
  params,
  searchParams,
}: {
  params: Promise<{ symbol: string }>;
  searchParams: Promise<{ period?: string }>;
}) {
  const { symbol } = await params;
  const { period: periodParam } = await searchParams;
  const ticker = decodeTicker(symbol);
  return (
    <StatementMetricPage
      symbol={ticker}
      period={periodFrom(periodParam)}
      slug="operating-cash-flow"
      title={`${ticker} Operating Cash Flow`}
      description="Cash generated by operations from the cash flow statement."
      field="operatingCashFlow"
      kind="cash"
      ttmField="operatingCashFlow"
    />
  );
}
