import { RatioMetricPage, periodFrom } from "@/components/ratio-metric-page";

export default async function RoicPage({
  params,
  searchParams,
}: {
  params: Promise<{ symbol: string }>;
  searchParams: Promise<{ period?: string }>;
}) {
  const { symbol } = await params;
  const { period: periodParam } = await searchParams;
  const ticker = symbol.toUpperCase();
  return (
    <RatioMetricPage
      symbol={ticker}
      period={periodFrom(periodParam)}
      slug="roic"
      title={`${ticker} Return on Invested Capital`}
      description="Operating return generated by debt and equity capital."
      field="returnOnInvestedCapital"
      ttmField="returnOnInvestedCapitalTTM"
      valueLabel="ROIC"
      formula="ROIC = NOPAT ÷ Invested Capital"
      format="percent"
      source="metrics"
    />
  );
}
